### ISSUE TITLE
Ubuntu 15.04 doesn't work anymore

### ISSUE THREAD

**Issue by fitz123** [seriyps/NetworkManager-l2tp#35]

**Comment by kometchtech** [comment]
Hope I will work Ubuntn 15.04.

**Comment by seriyps** [comment]
Sorry, guys. Looks like I have not enough free time and motivation to continue supporting this plugin. It requires some rewrite to make it work on 15.04, since Ubuntu now uses StrongSwan instead of OpenSwan. It's not just 'change version number and push old sources as new package to PPA repo' now.
Also, I now don't use this plugin for myself, and it's significantly harder to work on thing you personaly doesn't need.

**Comment by Ecno92** [comment]
Maybe less applicable to the issue itself, but are there any useable alternatives which we can use until someone can fix this? 

I've used this project in the past with success, but since I moved to the newest Ubuntu version I'm unable to connect to VPN without workarounds. It would be nice to have something until this issue is resolved. :smile:

**Comment by seriyps** [comment]
Project development was moved to https://github.com/nm-l2tp/network-manager-l2tp
If you feel that this problem wasn't resolved, please, re-create this issue on this new project.
